name: Deploy Opita Developer Web

on:
  push:
    branches:
      - main
    paths:
      - 'opita-developer-web/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'opita-developer-web/package-lock.json'

      - name: Install Dependencies
        working-directory: opita-developer-web
        run: npm ci

      - name: Build Astro Project
        working-directory: opita-developer-web
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to S3
        working-directory: opita-developer-web/dist
        run: aws s3 sync . s3://developer.opitacode.com --delete --cache-control "max-age=14400"

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id E297ZMSJM7FP9V --paths "/*"
